name: Linting

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: flake8
        run: flake8 --max-line-length 100 .
      - name: isort
        run: isort --diff --check .
